# Generated by Django 4.2.3 on 2023-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
