# Generated by Django 4.2.3 on 2023-10-07 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_profile_name_delete_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                validators=[
                    django.core.validators.MaxLengthValidator(limit_value=500)
                ]
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
